sonar.projectKey=VidiomTM_coverforge-trainer
sonar.organization=vidiomtm
sonar.qualitygate.wait=true

# Source paths
sonar.sources=src/coverforge_trainer
sonar.tests=tests

# Coverage
sonar.python.coverage.reportPaths=coverage.xml
